Repository 2024-Winter-BootCamp-TeamD/review-Frontend, pull requests merged in 2025-01, with the labels that each got.

#5 [feat/#3] 알림 버튼 구현
  package-lock.json
  package.json
  src/components/NotificationButton.jsx
Labels: 기능구현, 디자인

#8 [feat/#6] 서치 바 제작
  src/components/SearchBar.css
  src/components/SearchBar.jsx
Labels: 디자인

#9 [feat/#7] 서치 바(Alternative Version) 제작
  src/components/SearchBarAlt.css
  src/components/SearchBarAlt.jsx
Labels: 디자인

#11 [feat/#4]: 모드선택 버튼 제작
  src/components/ModeselectButton/Modeselectbutton.css
  src/components/ModeselectButton/Modeselectbutton.jsx
Labels: 디자인

#13 [feat/#10] 모달창 구현
  src/components/SelectionModal.css
  src/components/SelectionModal.jsx
  src/components/SelectionModalItem.css
  src/components/SelectionModalItem.jsx
Labels: 디자인

#20 [docs/#19] 파일 경로 수정 및 라우팅 설정
  package-lock.json
  src/App.css
  src/App.jsx
  src/components/NotificationButton/NotificationButton.jsx
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBarAlt/SearchBarAlt.css
  src/components/SearchBarAlt/SearchBarAlt.jsx
  src/components/SelectModal/SelectionModal.css
  src/components/SelectModal/SelectionModal.jsx
  src/components/SelectionModalItem/SelectionModalItem.css
  src/components/SelectionModalItem/SelectionModalItem.jsx
  src/components/Sidebar.css
  src/components/Sidebar/Sidebar.css
  src/components/Sidebar/Sidebar.jsx
  src/components/SidebarButton/SidebarButton.css
  src/components/SidebarButton/SidebarButton.jsx
  src/pages/History.jsx
  src/pages/Home.jsx
  src/pages/Report.jsx
  src/pages/Repositories.jsx
Labels: 리팩토링, 문서화

#23 Design/#17 대시보드 창 구현
  package-lock.json
  package.json
  src/App.jsx
  src/components/ModeselectButton/Modeselectbutton.css
  src/components/ModeselectButton/Modeselectbutton.jsx
  src/components/Sidebar/Sidebar.jsx
  src/index.css
  src/main.jsx
  src/pages/Dashboard.css
  src/pages/Dashboard.jsx
Labels: 기능구현, 디자인

#25 [feat/#18] history페이지 구현
  package-lock.json
  package.json
  src/App.jsx
  src/components/Chart/Chart.css
  src/components/Chart/Chart.jsx
  src/components/Reviews/Reviews.css
  src/components/Reviews/Reviews.jsx
  src/components/SearchBar/SearchBar.css
  src/pages/History.css
  src/pages/History.jsx
Labels: 기능구현, 디자인

#30 [Refactor/#28]페이지 디자인 디테일 수정
  src/components/Chart/Chart.css
  src/components/Chart/Chart.jsx
  src/components/ModeselectButton/Modeselectbutton.css
  src/components/Reviews/Reviews.css
  src/components/Reviews/Reviews.jsx
  src/components/Sidebar/Sidebar.css
  src/components/SidebarButton/SidebarButton.css
  src/pages/Dashboard.css
  src/pages/Dashboard.jsx
  src/pages/History.css
  src/pages/History.jsx
Labels: 리팩토링

#32 Design/#27 플로팅 버튼 구현
  src/FloatingButton/FloatingButton.css
  src/FloatingButton/FloatingButton.jsx
Labels: 디자인

#36 [Style/#35] Styled component형식으로 변환
  src/App.css
  src/components/Chart/Chart.css
  src/components/Chart/Chart.jsx
  src/components/ModeselectButton/Modeselectbutton.css
  src/components/ModeselectButton/Modeselectbutton.jsx
  src/components/NotificationButton/NotificationButton.jsx
  src/components/ReportList/ReportList.css
  src/components/ReportList/ReportList.jsx
  src/components/Reviews/Reviews.css
  src/components/Reviews/Reviews.jsx
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBarAlt/SearchBarAlt.css
  src/components/SearchBarAlt/SearchBarAlt.jsx
  src/components/SelectModal/SelectionModal.css
  src/components/SelectModal/SelectionModal.jsx
  src/components/SelectionModalItem/SelectionModalItem.css
  src/components/SelectionModalItem/SelectionModalItem.jsx
  src/pages/History.css
  src/pages/History.jsx
  src/pages/Home.jsx
  src/pages/Report.jsx
  src/pages/Repositories.jsx
Labels: 리팩토링

#38 [Refactor/#37] 디자인 수정
  src/components/Chart/Chart.jsx
  src/components/Reviews/Reviews.jsx
  src/components/Sidebar/Sidebar.css
  src/components/Sidebar/Sidebar.jsx
  src/pages/Home.jsx
Labels: 리팩토링, 디자인

#40 [Feat/#33] 로딩 인디케이터 구현
  package-lock.json
  package.json
  src/App.jsx
  src/components/LoadingIndicator/LoadingIndicator.jsx
  src/components/LoadingIndicator/LoadingIndicator.module.css
  src/pages/Home.jsx
Labels: 기능구현

#45 Refactor/#43 반응형으로 수정
  src/components/ModeselectButton/Modeselectbutton.jsx
  src/components/Sidebar/Sidebar.css
  src/pages/Dashboard.css
  src/pages/Report.jsx
Labels: 리팩토링

#46 [Fix/#44] 히스토리 페이지 수정
  src/components/Chart/Chart.jsx
  src/components/Reviews/Reviews.jsx
  src/pages/History.jsx
Labels: 리팩토링

#54 Desgin/#53 알림버튼 디자인 수정
  src/App.jsx
  src/assets/SleepingCat.svg
  src/components/NotificationButton/NotificationButton.jsx
  src/pages/Dashboard.css
  src/pages/Report.jsx
Labels: 디자인

#57 [feat/#56] repository페이지api 연동완료
  package-lock.json
  package.json
  src/pages/Repositories.jsx
  src/services/api.jsx
  src/services/repositoryService.jsx
Labels: 기능구현

#60 Feat/#58 Report페이지 api연동 완료
  src/components/PlayfulButton.jsx
  src/pages/Report.jsx
  src/pages/Repositories.jsx
  src/services/ReportService.jsx
Labels: 기능구현

#62 [Feat/#59] History 페이지 api연동
  src/components/Chart/Chart.jsx
  src/components/Reviews/Reviews.jsx
  src/pages/History.jsx
  src/services/prReviewService.jsx
Labels: 기능구현

#64 Feat/#55 Dashboard API 연동
  package-lock.json
  package.json
  src/pages/Dashboard.jsx
  src/services/DashboardService.jsx
Labels: 기능구현

#65 [Feat/#61] Report페이지 그래프 시각화 제외 전부 연동 완료
  src/pages/Report.jsx
  src/services/ReportService.jsx
Labels: 기능구현

#67 [Feat/#34] 프론트 익스텐션 배포 적용
  extension/background.js
  extension/content.css
  extension/content.js
  extension/icons/icon128.png
  extension/icons/icon16.png
  extension/icons/icon48.png
  extension/manifest.json
  extension/popup.css
  extension/popup.html
  extension/popup.js
  package-lock.json
  package.json
  popup.css
  popup.html
  public/popup.html
  src/App.jsx
  src/ExtensionApp.jsx
  src/FloatingButton/FloatingButton.css
  src/components/Sidebar/Sidebar.css
  src/components/Sidebar/Sidebar.jsx
  src/components/SidebarButton/SidebarButton.css
  src/main.jsx
  src/pages/History.jsx
  src/pages/Report.jsx
  src/pages/Repositories.jsx
  src/popup.css
  src/popup.jsx
  src/services/DashboardService.jsx
  src/services/ReportService.jsx
  src/services/prReviewService.jsx
  src/services/repositoryService.jsx
  vite.config.js
Labels: 기능구현

#70 [Style/#63] 폰트적용 및 디자인 개선
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/ExtensionApp.jsx
  src/components/LoadingIndicator/LoadingIndicator.jsx
  src/components/ModeSwitchButton/ModeSwitchButton.jsx
  src/components/ModeselectButton/Modeselectbutton.jsx
  src/components/Reviews/Reviews.jsx
  src/components/Sidebar/Sidebar.css
  src/components/Sidebar/Sidebar.jsx
  src/components/SidebarButton/SidebarButton.css
  src/pages/Dashboard.css
  src/pages/Dashboard.jsx
  src/pages/History.jsx
  src/pages/Home.jsx
  src/pages/Report.jsx
  src/pages/Repositories.jsx
Labels: 기능구현, 리팩토링, 디자인

#72 Feat/#66 리포트 페이지 개선
  package-lock.json
  package.json
  src/pages/Dashboard.jsx
  src/pages/Report.jsx
Labels: 기능구현, 디자인

#73 [Feat/#68] 부분 코드 리뷰 기능 구현
  extension/content.css
  extension/content.js
  extension/manifest.json
Labels: 기능구현

#76 [Feat/#74] 알림메시지 연동 및 오류 해결
  package-lock.json
  src/App.jsx
  src/components/Chart/Chart.jsx
  src/components/NotificationButton/NotificationButton.jsx
  src/main.jsx
  src/pages/Dashboard.jsx
  src/pages/History.jsx
  src/services/repositoryService.jsx
Labels: 기능구현, 이슈해결

#80 [REFACTOR] 익스텐션 버튼 정렬 수정 리팩토링
  extension/content.js
  extension/icons/basic.png
  extension/icons/clean.png
  extension/icons/dashboard.png
  extension/icons/newbie.png
  extension/icons/optimize.png
  extension/icons/study.png
  extension/manifest.json
Labels: 기능구현, 리팩토링

#82 [Refactor/#77] 부분코드리뷰 디자인 수정, 기능 추가
  extension/content.css
  extension/content.js
  src/pages/Dashboard.jsx
Labels: 기능구현, 디자인

#85 Refactor/#77 모달창 재조정
  extension/content.css
  extension/content.js
Labels: 디자인
